
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package tareaast3d;

/** CUP generated class containing symbol constants. */
public class SymbolCode {
  /* terminals */
  public static final int div = 8;
  public static final int decimal = 12;
  public static final int EOF = 0;
  public static final int menos = 6;
  public static final int pa_c = 3;
  public static final int numero = 11;
  public static final int pa_a = 2;
  public static final int error = 1;
  public static final int por = 7;
  public static final int punto_coma = 4;
  public static final int identificador = 10;
  public static final int mas = 5;
  public static final int igual = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pa_a",
  "pa_c",
  "punto_coma",
  "mas",
  "menos",
  "por",
  "div",
  "igual",
  "identificador",
  "numero",
  "decimal"
  };
}

